server:
  port: 8005
spring:
  # redis配置
  redis:
    cluster:
      nodes: 192.168.64.201:7011,192.168.64.201:7012,192.168.64.201:7013,192.168.64.201:7014,192.168.64.201:7015,192.168.64.201:7016
      max-redirects: 3
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数
        max-idle: 10      # 连接池最大空闲连接
        min-idle: 5       # 连接池最小空闲连接
        max-wait: -1ms    # 连接池最大阻塞时间
    timeout: 3000ms
    password: 123456

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: redis:session
  application:
    name: xxx-service-demo-redis


# eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
