server:
  port: 8003
spring:
  application:
    name: xxx-service-demo-canal
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

canal:
  client:
    instances:
      example:
        host: 192.168.64.201
        port: 11111
        batchSize: 1000