server:
  port: 7002
spring:
  application:
    name: xxx-gateway-demo
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: xxx-service-demo
          uri: lb://xxx-service-demo
          predicates:
            - Path=/goods/**

        - id: xxx-web-demo
          uri: lb://xxx-web-demo
          predicates:
            - Path=/brand/**
          filters:
            #            - StripPrefix= 1
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: xxx-service-system
          uri: lb://xxx-service-system
          predicates:
            - Path=/system/**
          filters:
            #            - StripPrefix= 1
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  # 配置Redis 127.0.0.1可以省略配置
  redis:
    host: 192.168.64.201
    port: 6379
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

