server:
  port: 7002
spring:
  application:
    name: xxx-gateway-demo
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: xxx-service-demo
          uri: lb://xxx-service-demo
          predicates:
            - Path=/goods/**
#          filters:
#            - StripPrefix= 1
        - id: xxx-web-demo
          uri: lb://xxx-web-demo
          predicates:
            - Path=/brand/**
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

